### ISSUE TITLE
Problem with rails 5.0.0.rc1 : must use Sinatra master branch

### ISSUE THREAD

**Issue by kofronpi** [statianzo/que-web#19]
Adding `gem 'que-web'` to a Rails `5.0.0.rc1` with ruby `2.3.1` make rails crash at startup:

```
/home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- rack/showexceptions (LoadError)
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/que-web-0.4.0/lib/que/web.rb:1:in `<top (required)>'
  from /home/username/.rvm/gems/ruby-2.3.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
  from /home/username/.rvm/gems/ruby-2.3.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
  from /home/username/.rvm/gems/ruby-2.3.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
  from /home/username/.rvm/gems/ruby-2.3.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
  from /home/username/.rvm/gems/ruby-2.3.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
  from /home/username/.rvm/gems/ruby-2.3.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
  from /home/username/project/ex/config/application.rb:7:in `<top (required)>'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `require'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `tap'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `server'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /home/username/project/ex/.bundle/ruby/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

I think this is related to this Sinatra issue: https://github.com/sinatra/sinatra/issues/1055 and that one should use the master branch to support rails >= 5.0.0

The documentation may need to be updated.

Thanks,

**Comment by statianzo** [comment]
Fixed by #20
